[script:entropy_upload]
match = /entropy_upload
script = upload_handler.py
scripttype = persist
handler = upload_handler.UploadHandler
requireAuthentication = true
output_modes = json
passPayload = true
passHttpHeaders = true
python.version = python3

[script:entropy_lab]
match = /entropy_lab
script = lab_handler.py
scripttype = persist
handler = lab_handler.LabHandler
requireAuthentication = true
output_modes = json
passPayload = true
passHttpHeaders = true
python.version = python3
